services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shorterUrlDb
      - SPRING_DATASOURCE_USERNAME=shorterUrlDb
      - SPRING_DATASOURCE_PASSWORD=shorterUrlDb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: shorterUrlDb
      POSTGRES_PASSWORD: shorterUrlDb
      POSTGRES_DB: shorterUrlDb
    ports:
      - "${POSTGRES_DATABASE_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:

  redis-data:
    driver: local
  db-data:
    driver: local